### ISSUE TITLE
게시글 조회수 기능 추가

### ISSUE THREAD

**Issue by jichanan** [jichanan/danbi#9]
## Due date
> 2023-03-31 까지

## 구현방법
IP주소, Cookie, Local Storage, Session 중 택 1 <br>
사용자를 식별하여 게시글 조회 후 24시간동안  조회수가 올라가지 않도록 구현하는 것이 목표입니다. (어뷰징 방지)

## 작업내용
![hits](https://user-images.githubusercontent.com/103406525/229286494-8ec018ee-1b2e-4b62-b9b7-64a2d8c61c0e.PNG)

## 스크린샷
![hits](https://user-images.githubusercontent.com/103406525/229286189-831c2e17-b3cd-46fd-80c9-dccac8fc8648.PNG)

**Comment by jichanan** [comment]
## [python] time vs datetime
둘 다 시간과 관련된 모듈 → 날짜와 관련된 기능은 주로 datetime, 시간과 관련된 기능은 주로 time

### example <br>
1.  **time** : time.sleep()함수는 굉장히 많이 사용되는 기능이며 어렵지 않으므로 외워두기!
`import time`
`print("지금부터 5초 동안 정지합니다.")`
`time.sleep(5)`
`print("프로그램을 종료합니다")` 
2. **datetime** : timedelta(), strftime(), strptime() ← datetime모듈에서는 이 3가지 함수가 많이 사용됩니다.
`pass`

**Comment by SooDevv** [comment]
> [python] time vs datetime
> time : time.sleep()함수는 굉장히 많이 사용되는 기능이며 어렵지 않으므로 외워두기!

- time.sleep() 의 경우는 주로 크롤링할때 많이 사용되는데, 크롤링은 웹페이지에 데이터를 요청해서 가져오는거자나 
근데 쉬는시간없이 많은 데이터를 가져오면 DDOS 공격이라고 판단할 수도 있고, 그 웹페이지 서버에 부하를 주기때문에 
sleep() 을 쓰는 편이야!
